-- Valor total das vendas e dos fretes por produto e ordem de venda
-- Valor de venda por tipo de produto
-- Quantidade e valor das vendas por dia, mês, ano
-- Lucro dos meses
-- Venda por produto
-- Venda por cliente, cidade do cliente e estado
-- Média de produtos vendidos
-- Média de compras que um cliente faz
